# api/config/api_platform/resources.yaml
resources:
  App\Core\Entity\Article:
    attributes:
      input: App\Core\Dto\ArticleInputDto
      output: App\Core\Dto\ArticleOutputDto
    collectionOperations:
      post: ~
      get: ~
    itemOperations:
      get: ~
  App\User\Entity\User:
    collectionOperations:
      post: ~
      password_reset_request:
        input: App\User\ForgetPassword\PasswordResetRequest
        path: "reset_password_request"
        messenger: "input"
        method: POST
        output: false
      password_reset:
        input: App\User\ForgetPassword\PasswordReset
        path: "reset_password"
        messenger: "input"
        method: POST
        output: false
    itemOperations:
      get: ~