# api/config/api_platform/resources.yaml
resources:
  App\Core\Entity\Article:
    attributes:
      input: App\Core\Dto\ArticleInputDto
      output: App\Core\Dto\ArticleOutputDto
    collectionOperations:
      post: ~
      get: ~
    itemOperations:
      get: ~
  App\User\Entity\User:
    collectionOperations:
      reset_password:
        input: App\User\ForgetPassword\ForgetPassword
        path: "forget_password"
        messenger: "input"
        method: POST
        output: false
    itemOperations: []